name: Run Kibot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pcbdraw
        pip install svgpathtools
        sudo apt install kicad -y
    - name: Creating the diagram
      run: |
        pcbdraw *.kicad_pcb doc/board.png
        git add doc/board.png
        git commit -m "Added board.png"
        
